name: update-trends-resource

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "update branch"
        required: true
        type: string
      github_token:
        description: "github_token"
        required: true
        type: string
      key:
        description: "object key"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout data branch
        uses: actions/checkout@v3
        with:
          repository: realtime-trends/realtime-trends-data
          path: data
          ref: ${{ github.event.inputs.branch }}
          token: ${{ github.event.inputs.github_token }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7.17"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      # sudo apt install -y ./google-chrome-stable_current_amd64.deb
      # rm -f ./google-chrome-stable_current_amd64.deb

      # - name: Install chrome
      #   run: |
      #     sudo apt install -y chromium-chromedriver

      - name: Run script
        run: python main.py

      - name: Push to git
        working-directory: data
        env:
          BRANCH: ${{ github.event.inputs.branch }}
          REPO_USER: github-actions[bot]
          REPO_KEY: ${{ github.event.inputs.github_token }}
        run: |
          git checkout --orphan tmp
          git branch -D $BRANCH
          git branch -m $BRANCH
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git commit -am "update: Update trends resource file"
          git push https://$REPO_USER:$REPO_KEY@github.com/realtime-trends/realtime-trends-data.git $BRANCH:$BRANCH -f
