name: Update trends data

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.SUBMODULE_TOKEN }}
        submodules: true    
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry        
    - name: Run upadater
      run: |
        poetry install --no-dev
        poetry run python main.py
    - name: Set git config
      run: |
        git config --global user.email "hoya.develop@gmail.com"
        git config --global user.name "Changho Park"
    - name: Commit trend.json
      working-directory: data
      run: |
        git add trends.json
        git commit -m "update: trends update."
        git push -f
    - name: Push trend.json
      run: |
        git add data
        git commit -m "update: trends update."
        git push -f
